current_shows = [
    "Lagnachi Bedi",
    "Muramba",
    "Mulgi Zali Ho",
    "Swabhimaan",
    "Sahakutumba Sahaparivar",
    "Aai Kuthe Kay Karte",
    "Rang Majha Vegla",
    "Phulala Sugandh Maticha",
    "Tujhech Mi Geet Gaat Ahe",
    "Sukh Mhanje Nakki Kay Asta",
    "Thipkyanchi Rangoli",
    "Aboli",
    "Pinkycha Vijay Aso",
    "Me Honar Superstar Aawaj Konacha Maharashtracha",
    "Nave Lakshya",

    "Satyavan Savitri",
    "Man Udu Udu Jhala",
    "Tu Tevha Tashi",
    "Majhi Tujhi Reshimgath",
    "Tujhya Majhya Sansarala Ani Kai Hava",
    "Chala Hawa Yeu Dya",
    "Masaledar Kitchen Kallakar",
    "Band Baja Varat - Zee Marathicha Aher Tumchya Gharat",
    "Devmanus S2",

    "Padmavati",
    "Geeta",
    "Lajjat Maharashtrachi",
    "Raja Ranichi Ga Jodi",
    "Yogyogeshwar Jai Shankar",
    "Balumamachya Navana Changbhala",
    "Jai Jai Swami Samarth",
    "Jeev Majha Guntala",
    "Sundara Manamadhye Bharali",
    "Bhagya Dile Tu Mala",
    "Aai Mayeche Kavach",
    "Lek Majhi Durga",

    "Dnyaneshwar Mauli",
    "Gatha Navanathanchi",
    "Swarajya Saudamini Tararani",
    "Sundar Amcha Ghar",
    "Boss Majhi Ladachi",
    "Kon Honar Karodpati",
    "Tumchi Mulgi Kay Karte",

    "Jai Hanuman",
    "Abhalachi Maya",
    "Jau Nako Dur Baba",
    "Majhi Manasa",
    "Kanyadaan",
    "Sant Gajanana Shegaviche",
    "Nandini",
    "Sundari"
]